### PR TITLE
fix typo in footer

### PR DESCRIPTION
**Pull request by cvan**

### CODE REVIEW

**Comment by ryanschmidt** [comment]
@cvan not sure of the process here but the commit looks ready for prod.

**Comment by cvan** [comment]
> @cvan not sure of the process here but the commit looks ready for prod.

thanks! I moved this commit to the `prod` branch so it's live now :smile:

**Comment by ryanschmidt** [comment]
Great! Sorry for sitting on this. Must have missed the initial PR notification.

**Pull request merged**
