### PR TITLE
#121 - Unminify CSS and Remove SASS folder

### PR DESCRIPTION
**Pull request by michaelic**
This PR fulfills https://github.com/mozilla/moz-games/issues/121
@cvan Could you please review?

### CODE REVIEW

**Comment by cvan** [comment]
many thanks for the contribution! I wanted to get around to doing this, so big thanks 👍

**Comment by cvan** [comment]
in the [`package.json` file], can you remove the `shx rm -rf _build/assets/sass` command from the [`build` script](https://github.com/mozilla/moz-games/blob/bc4deba/package.json#L13)?

**Comment by cvan** [comment]
also, can you remove [`.sass-cache` line](https://github.com/mozilla/moz-games/blob/bc4deba/.gitignore#L2) from the [`.gitignore` file](https://github.com/mozilla/moz-games/blob/bc4deba/.gitignore)?

**Comment by cvan** [comment]
really nice job on this. I checked the styles, and everything looks unchanged when you moved over the SASS to CSS. awesome work! 👍

**Comment by cvan** [comment]
btw, I addressed https://github.com/mozilla/moz-games/pull/145#issuecomment-334370904 and https://github.com/mozilla/moz-games/pull/145#issuecomment-334371052 in PR #146

**Comment by michaelic** [comment]
Hey @cvan, just wondering if you have any ideas about where else I might be useful in this project? I'm pretty comfortable with anything HTML / CSS / JS.

I was thinking about either of these two for starters, thoughts?:
https://github.com/mozilla/games.mozilla.org/issues/140
https://github.com/mozilla/games.mozilla.org/issues/134

**Comment by cvan** [comment]
I actually got #140 done locally last evening. I’ll push a PR soon and have you review, if you have a minute.

And #134 is a perfect issue to tackle.

Thanks for helping with these contributions - I really appreciate it.

**Pull request merged**
